spring:
  application:
    name: Demo
  datasource:
    url: jdbc:mysql://localhost:3306/alami?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: "Mas%83rra"
  data:
    rest:
      base-path: /rest/api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  profiles:
    active: production
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
logging:
  file: logs/report_api.log
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
    console: "%d %-5level %logger : %msg%n"
server:
  port: 8086
  servlet:
    context-path: /